### ISSUE TITLE
Update to `@tanstack/react-query`

### ISSUE THREAD

**Issue by Todomir** [ecyrbe/zodios-react#112]
React Query package is now being updated as [@tanstack/react-query](https://www.npmjs.com/package/@tanstack/react-query), making this package incompatible to anyone using the new `@tanstack/react-query` package instead of `react-query`.

**Comment by ecyrbe** [comment]
Yes Indeed. I'm still undecided about what to do.
I know some users are still in V3.
I don't want to impose a migration on anyone.
This is so impactfull that i think i'll need to also create a separate :. 
`@zodios/tanstack-react` 
And maintain both for at least a few month with a deprecation warning

**Comment by ecyrbe** [comment]
I'll update you soon on this topic

**Comment by Todomir** [comment]
No worries

**Comment by ecyrbe** [comment]
So After exchanging with the maintainer of react query, we only know to ways of migrating:
- create a parralel library like `@zodios/react-query`
- create a major version of `@zodios/react`

So for now i think i'll take the second option. This might  take some time.
Indeed, i plan to also rework zodios api definition to make it simpler to write. This will be a breaking change.
So in the mean time, i'll create a beta of `@zodios/react` v10 to allow early migration to tanstack query v4
