### ISSUE TITLE
Handling errors

### ISSUE THREAD

**Issue by ivenuss** [ecyrbe/zodios-react#234]
Hi,

I would like to ask, if this is correct typing of Zodios error type.

The default type of `error` in `onError` callback is: `error: Error | ZodiosError | AxiosError<unknown, any> | null`.

This error object does not have assigned `ErrorResponseSchema` type which it should have (it has `uknown` type). The actual reponse is `AxiosError` object which doesn not contain `ErrorResponseSchema` type.

Do I structure my **OpenAPI** wrong? 

```js
// Schema
const ErrorResponseSchema = z.object({
  statusCode: z.number().int(),
  message: z.string().optional(),
  error: z.string()
});

// Generated object
{
  method: 'post',
  path: '/api/...',
  requestFormat: 'json',
  parameters: [],
  response: z.string(),
  errors: [
    {
      status: 400,
      schema: ErrorResponseSchema
    }
  ]
}
```
```yaml
/api/...:
  post:
    operationId: someid
    parameters:
      ...
    requestBody:
      ...
    responses:
      '201':
        content:
          application/json:
            schema:
              type: string
      '400':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponseSchema'
    tags: *ref_1
```

**Comment by ecyrbe** [comment]
nothing wrong actually, zodios did not yet infer error type correctly with react-query.
This will be fixed on v11 where type will be correctly inferred.
So at the moment you need to typecast it with `as` keyword

**Comment by ecyrbe** [comment]
oh, actually, thinking about it a can backport it to v10.
