### ISSUE TITLE
"select" and "enabled" options doesn't seem to work

### ISSUE THREAD

**Issue by DylanMerigaud** [ecyrbe/zodios-react#270]
Hi, first time that I try this lib, I used it with the two options that I use without any issues with react-query, "select" and "enabled".
But setting enabled to false, or setting a selected to change the returned data doesn't work, is it a known issue ? Is there a workaround ?

![image](https://user-images.githubusercontent.com/1936984/223148335-6f7cc738-c9e3-48e4-92ca-8d05fab0fd83.png)

**Comment by ecyrbe** [comment]
it's because react query parameters are the third parameter of the function. Please read the docs before jumping to coding : 
http://www.zodios.org/docs/client/react#zodiosusequery

**Comment by DylanMerigaud** [comment]
Sorry, there was no Typescript error so I havent noticed ! Gread job for the lib !
