### ISSUE TITLE
[Improvement] Enabling suspense

### ISSUE THREAD

**Issue by austins** [ecyrbe/zodios-react#321]
Allow enabling React Query's suspense setting via ZodiosHooks options argument and have the types inferred correctly. Ensure that it can be opted-out on a per-query basis.

Also, if suspense is enabled on a per-query basis via useQuery, the inferred type doesn't get updated to status and error.

This will also be particularly useful for Next.js' new app router loading/error states.

**Comment by ecyrbe** [comment]
Can you share a more detailed example and expectation details. Zodios is just a react query helper and should supports react-query suspens option out of the box already.

**Comment by austins** [comment]
Hmm, you're right. I thought the suspense option would infer the the data type as not undefined.

![image](https://user-images.githubusercontent.com/1623983/233801940-65ee8f14-1ca9-46cb-a5cb-e21b1afd6392.png)

I was thinking more of tRPC's [experimental suspense](https://trpc.io/docs/reactjs/suspense) where it does do that and returns an array, but I guess their wrapper does more special things.
