### ISSUE TITLE
useInfiniteQuery does not work when using template literal in endpoint path

### ISSUE THREAD

**Issue by not-paul-v** [ecyrbe/zodios-react#381]
Hi,

big fan of the library so far.

Unfortunately I ran into an issue regarding infinite queries.
Our backend consists of multiple micro services. I need to be able to swap out the base url for each service individually so I use the whole url as a path value in `makeEndpoint`.

Example:
```typescript
export const getSpaces = makeEndpoint({
    method: "get",
    path: `${SPACE_SERVICE_BASE_URL}api/v1/spaces`,
    response: PaginatedSpacesSchema,
    parameters: PaginationParamsSchema,
    alias: "getSpaces",
});
```
(SPACE_SERVICE_BASE_URL is something like https://foobar.com/)

This works well when calling the `getSpaces` on the client object or `useGetSpaces`.

Because of the template literal the type of the path is `"${any}api/v1/spaces"`. So in theory I should be able to call `useInfiniteQuery` like the following if I am not mistaken:

`hooks.useInfiniteQuery("${any}api/v1/spaces", {queries: {...}})`

Unfortunately `useInfiniteQuery` doesn't work if the path type comes from a string with a template literal. ("No endpoint found for ..." and the types for the config parameters etc. don't work).

If this is the expected behavior / a typescript limitation, is there a way to the set a base url for a multiple endpoints?

If you need any additional infos let me know. I am also willing to help out with a PR if needed.

Thank you in advance, keep up the good work.

**Comment by ecyrbe** [comment]
Hello,

If Base path is only known at runtime, zodios and typescript can't infer it.
Use zodios client base path constructor parameters for this.

```ts
const client = new Zodios(SPACE_SERVICE_BASE_URL, apidef);
```
If it's known at compile time (not a good practice), just declare your base path like this: 

```ts
const SPACE_SERVICE_BASE_URL = 'https://base' as const;
```
