### ISSUE TITLE
"invalidate" property missing when using alias hooks

### ISSUE THREAD

**Issue by brendenmoore** [ecyrbe/zodios-react#87]
`const { isLoading, data, invalidate } = zodiosHook.useGet("users/:userId", { params: { userId: userId } });`
^ works

`const { isLoading, data, invalidate } = zodiosHook.useGetUser({ params: { userId: userId } });`
^ gives me a red squiggly under "invalidate"

ts error: 
Property 'invalidate' does not exist on type 'UseQueryResult<{ merchantId?: string | null | undefined; paypalId?: string | null | undefined; logoUrl?: string | null | undefined; displayTitle?: string | null | undefined; description?: string | null | undefined; ... 24 more ...; passwordResetCount: number; }, unknown>'.ts(2339)

**Comment by ecyrbe** [comment]
Good catch. I'll fixe this today

**Comment by ecyrbe** [comment]
@brendenmoore fixed in version 9.0.1 of `@zodios/react`
